-- Retired: all Supabase Auth accounts now have immediate staff access.
-- Create accounts through Supabase Authentication > Users. No SQL grant is needed.
-- Apply migrations before using the app; keep public signup disabled.
