import { expect, test, type Page } from '@playwright/test'

const member = { id: 2, first_name: 'Justin', last_name: 'Wu', name: 'Justin Wu', status: 'staff', has_current_data: true, current_title: null, current_activities: ['Drill'],
 years_active: ['2023-24'], levels: [{name:'Friend',outcome:'basic',year:'2023-24'},{name:'Companion',outcome:'incomplete',year:null}], birth_date:'2000-01-02',notes:'Existing notes' }
const fixture = {...member,staff_history:{id:1,pathfinder_id:2,history:[{year:'2025-26',titles:['Friend Counselor','Drill Instructor']}]},
 drill:[{id:1,years:['2023-24'],team:'Precision',history_role:'pathfinder'},{id:2,years:['2025-26'],team:'Adult',history_role:'staff'}],
 drum_corps:[{history:[{year:'2023-24',drums:['Snare']}],history_role:'pathfinder'}],
 pbe:[{history:[{year:'2021-22',books:['1 Kings','Ruth']}],history_role:'pathfinder'}],
 tlt:[{history:[{year:'2023-24',operations:['Teaching']}],history_role:'pathfinder'}],
 red_zone_drill_performance:[],red_zone_drum_performance:[],red_zone_honor_evaluations:[],red_zone_bible_events:[],red_zone_knots:[],red_zone_tents:[],red_zone_jump_rope:[],red_zone_archery:[],red_zone_lashing:[],
 red_zone_burning_twine:[{year:'2023-24',placement:'1st Place',history_role:'pathfinder'}]}
async function setup(page:Page) {
 const user={id:'00000000-0000-0000-0000-000000000001',email:'staff@example.test',aud:'authenticated',role:'authenticated',app_metadata:{},user_metadata:{},created_at:'2026-01-01T00:00:00Z'}
 await page.route('http://127.0.0.1:54321/auth/v1/**',route=>route.fulfill({json:{access_token:'test-token',refresh_token:'test-refresh',token_type:'bearer',expires_in:3600,user}}))
 await page.route('http://127.0.0.1:54321/rest/v1/member_search?**',route=>route.fulfill({json:[member],headers:{'access-control-expose-headers':'content-range','content-range':'0-0/1'}}))
 await page.route('http://127.0.0.1:54321/rest/v1/pathfinders?**',route=>route.fulfill({json:route.request().method()==='PATCH'?{id:2}:fixture}))
 await page.goto('/')
 await page.getByLabel('Email',{exact:true}).fill('staff@example.test')
 await page.getByLabel('Password',{exact:true}).fill('test-password')
 await page.getByRole('button',{name:'Sign in',exact:true}).click()
 await expect(page.getByRole('button',{name:'Open profile for Justin Wu'})).toBeVisible()
}

test('Add Record saves once, keeps failures editable, and refreshes Search',async({page})=>{
 await setup(page)
 await page.route('**/rest/v1/rpc/current_club_year',route=>route.fulfill({json:'2026-27'}))
 await page.route('**/rest/v1/staff_titles?**',route=>route.fulfill({json:['Club Director','Friend Counselor','Companion Counselor','Drill Instructor','Drum Corps Leader','Master Guide Leader'].map(title=>({title}))}))
 const requests: Record<string,unknown>[]=[]
 let release: (()=>void) | undefined
 await page.route('**/rest/v1/rpc/add_member_record',async route=>{
  requests.push(route.request().postDataJSON())
  if(requests.length===1) return route.fulfill({status:409,json:{code:'23505',message:'A profile with this first and last name already exists. Find the existing profile in Search.'}})
  await new Promise<void>(resolve=>{release=resolve})
  await route.fulfill({json:42})
 })
 await page.getByRole('button',{name:'Add / Edit Profiles',exact:true}).click()
 await page.getByRole('button',{name:'Add Record',exact:true}).click()
 const form=page.getByRole('dialog',{name:'Add Record',exact:true})
 await expect(form.getByLabel('Current Year')).toHaveValue('2026-2027')
 await form.getByLabel('First Name',{exact:true}).fill(' New ')
 await form.getByLabel('Last Name').fill('Member')
 await form.getByLabel('Birthday').fill('2001-02-03')
 await form.getByRole('combobox',{name:'Status',exact:true}).selectOption('Staff')
 await form.getByRole('combobox',{name:'Class/Title'}).click()
 await expect(form.locator('.level-name')).toHaveText(['Counselor','Instructor','Leader','Other'])
 await page.screenshot({path:'test-results/add-record-desktop.png',fullPage:true})
 await form.getByRole('option',{name:'Friend Counselor',exact:true}).click()
 await form.getByRole('option',{name:'Companion Counselor',exact:true}).click()
 await form.getByRole('button',{name:'Add',exact:true}).click()
 await form.getByRole('button',{name:/Confirm/}).click()
 const failure=page.getByRole('dialog',{name:'Unable to Add Record',exact:true})
 await expect(failure.getByRole('alert')).toContainText('A profile with this first and last name already exists.')
 await page.screenshot({path:'test-results/add-record-error.png',fullPage:true})
 await failure.getByRole('button',{name:'Back to form'}).click()
 await expect(form.getByLabel('First Name',{exact:true})).toHaveValue(' New ')
 await expect(page.getByRole('dialog',{name:'Record Added',exact:true})).toHaveCount(0)
 await form.getByRole('button',{name:'Add',exact:true}).click()
 await form.getByRole('button',{name:/Confirm/}).click()
 const pending=page.getByRole('dialog',{name:'Adding Record',exact:true})
 await expect(pending).toContainText('Saving the new profile')
 await page.screenshot({path:'test-results/add-record-loading.png',fullPage:true})
 await expect(pending.getByRole('button',{name:'Close',exact:true})).toBeDisabled()
 await page.keyboard.press('Escape')
 await expect(pending).toBeVisible()
 const refreshed=page.waitForRequest(r=>r.url().includes('/member_search?'))
 await expect.poll(()=>!!release).toBe(true)
 release!()
 const summary=page.getByRole('dialog',{name:'Record Added',exact:true})
 await expect(summary).toContainText('New Member')
 await expect(summary).toContainText('02/03/2001')
 await expect(summary).toContainText('Friend Counselor, Companion Counselor')
 await page.screenshot({path:'test-results/record-added.png',fullPage:true})
 await refreshed
 expect(requests).toHaveLength(2)
 expect(requests[0]).toEqual(requests[1])
 expect(requests[1]).toMatchObject({p_first_name:'New',p_last_name:'Member',p_birth_date:'2001-02-03',p_status:'staff',p_current_title:['Friend Counselor','Companion Counselor'],p_school_year:'2026-27'})
 await summary.getByRole('button',{name:'Close',exact:true}).click()
 await expect(page.getByRole('button',{name:'Add Record',exact:true})).toBeFocused()
})

test('Add confirmation expires and status changes clear incompatible titles',async({page})=>{
 await page.setViewportSize({width:390,height:844})
 await setup(page)
 await page.route('**/rest/v1/rpc/current_club_year',route=>route.fulfill({json:'2026-27'}))
 await page.route('**/rest/v1/staff_titles?**',route=>route.fulfill({json:[]}))
 let writes=0
 await page.route('**/rest/v1/rpc/add_member_record',route=>{writes++;return route.fulfill({json:43})})
 await page.getByRole('button',{name:'Add / Edit Profiles',exact:true}).click()
 await page.getByRole('button',{name:'Add Record',exact:true}).click()
 const form=page.getByRole('dialog',{name:'Add Record',exact:true})
 await form.getByLabel('First Name',{exact:true}).fill('Example')
 await form.getByRole('combobox',{name:'Status',exact:true}).selectOption('Pathfinder')
 const classSelect=form.getByRole('combobox',{name:'Class/Title'})
 await classSelect.selectOption('Friend')
 await classSelect.selectOption('Companion')
 await expect(classSelect).toHaveValue('Companion')
 await expect(classSelect.locator('option:checked')).toHaveCount(1)
 await form.getByRole('button',{name:'Add',exact:true}).click()
 await expect(form.getByRole('button',{name:/Confirm/})).toBeVisible()
 await form.getByRole('combobox',{name:'Status',exact:true}).selectOption('Parent')
 await expect(form.getByRole('button',{name:'Add',exact:true})).toBeVisible()
 await expect(form.getByLabel('Class/Title')).toBeDisabled()
 await page.screenshot({path:'test-results/add-record-mobile.png',fullPage:true})
 await form.getByRole('button',{name:'Add',exact:true}).click()
 await expect(form.getByRole('button',{name:'Add',exact:true})).toBeVisible({timeout:7000})
 expect(writes).toBe(0)
 await form.getByRole('button',{name:'Add',exact:true}).click()
 const request=page.waitForRequest('**/rest/v1/rpc/add_member_record')
 await form.getByRole('button',{name:/Confirm/}).click()
 expect((await request).postDataJSON()).toMatchObject({p_current_title:null,p_birth_date:null,p_status:'parent'})
 await expect(page.getByRole('dialog',{name:'Record Added',exact:true})).toContainText('N/A')
})

test('current results expose First Last Status Title and activities only',async({page})=>{
 await setup(page)
 await expect(page.getByRole('columnheader')).toHaveText(['First Name','Last Name','Status','Class/Titles','Current activities'])
 await expect(page.getByRole('row').last()).toContainText('Staff')
 await expect(page.getByRole('row').last()).toContainText('Not recorded')
 await expect(page.getByRole('row').last().getByRole('cell').last()).toHaveText('N/A')
 const status=page.getByRole('combobox',{name:'Status',exact:true})
 await expect(status.locator('option')).toHaveText(['Any','Pathfinder','Staff','Parent','Not Active'])
 const request=page.waitForRequest(r=>r.url().includes('status=eq.not_active'))
 await status.selectOption('Not Active')
 await page.getByRole('button',{name:'Search records'}).click()
 await request
})

test('role histories retain year detail links and nested honors focus',async({page})=>{
 await setup(page)
 await page.getByRole('button',{name:'Open profile for Justin Wu'}).click()
 const profile=page.getByRole('dialog',{name:'Member profile'})
 await expect(profile).toContainText('01/02/2000')
 const pf=profile.getByRole('region',{name:'Pathfinder history'})
 const staff=profile.getByRole('region',{name:'Staff history'})
 await expect(pf).toContainText('Friend (Basic)')
 await expect(pf).toContainText('Companion (Incomplete)')
 await expect(pf).toContainText('Year unknown')
 await expect(pf).toContainText('Precision')
 await expect(pf).not.toContainText('Adult')
 await expect(staff).toContainText('Adult')
 await expect(staff).toContainText('Friend Counselor, Drill Instructor')
 await profile.getByRole('button',{name:'View Honors'}).click()
 await expect(page.getByRole('dialog',{name:'Honors',exact:true})).toContainText('WIP')
 await page.keyboard.press('Escape')
 await expect(profile.getByRole('button',{name:'View Honors'})).toBeFocused()
 await page.keyboard.press('Escape')
 await expect(page.getByRole('button',{name:'Open profile for Justin Wu'})).toBeFocused()
})

test('Notes preserve paragraphs and report saves and failures',async({page})=>{
 await setup(page)
 await page.getByRole('button',{name:'Open profile for Justin Wu'}).click()
 const notes=page.getByLabel('Notes',{exact:true})
 await expect(notes).toHaveValue('Existing notes')
 await notes.fill('First sentence.\n\nSecond paragraph.')
 const request=page.waitForRequest(r=>r.method()==='PATCH')
 await page.getByRole('button',{name:'Save Notes'}).click()
 expect((await request).postDataJSON()).toEqual({notes:'First sentence.\n\nSecond paragraph.'})
 await expect(page.getByText('Notes saved',{exact:true})).toBeVisible()
 await page.route('**/rest/v1/pathfinders?**',route=>route.fulfill({status:500,json:{message:'Save unavailable'}}))
 await notes.fill('Keep this unsaved text')
 await page.getByRole('button',{name:'Save Notes'}).click()
 await expect(page.getByRole('alert')).toContainText('Save unavailable')
 await expect(notes).toHaveValue('Keep this unsaved text')
})

test('shared years constrain every category with OR bubbles and AND categories',async({page})=>{
 await setup(page)
 const years=page.getByRole('combobox',{name:'Years',exact:true})
 await years.fill('2023-24'); await years.press('Enter')
 const level=page.getByRole('combobox',{name:'Level Earned',exact:true})
 await level.fill('Friend')
 await expect(page.getByRole('option',{name:'Friend (2023-24)',exact:true})).toHaveCount(0)
 await page.getByRole('option',{name:'Friend / Basic',exact:true}).click()
 await level.fill('Friend / Advanced');await level.press('Enter')
 const activity=page.getByRole('combobox',{name:'Extracurricular',exact:true})
 await activity.fill('Drums / Snare');await activity.press('Enter')
 await activity.fill('TLT / Teaching');await activity.press('Enter')
 const event=page.getByRole('combobox',{name:'Red Zone Events',exact:true})
 await event.fill('Burning Twine / 1st Place');await event.press('Enter');await event.press('Escape')
 const request=page.waitForRequest(r=>r.url().includes('or='))
 await page.getByRole('button',{name:'Search records'}).click()
 const expression=new URL((await request).url()).searchParams.get('or')!
 expect(expression).toContain('(and(or(levels.cs.')
 expect(expression).toContain('),or(search_activity_details.cs.')
 expect(expression).toContain('),or(search_event_details.cs.')
 const decoded=expression.replaceAll('\\"','"')
 expect(decoded).toContain('"outcome":"basic","year":"2023-24"')
 expect(decoded).toContain('"outcome":"advanced","year":"2023-24"')
 expect(decoded).toContain('"name":"Drums","detail":"Snare","year":"2023-24"')
 expect(decoded).toContain('"name":"TLT","detail":"Teaching","year":"2023-24"')
 expect(decoded).toContain('"name":"Burning Twine","detail":"1st Place","year":"2023-24"')
 expect(expression).not.toContain('search_years')
 await page.getByRole('button',{name:'Clear filters'}).click()
 await expect(page.getByRole('button',{name:/^Remove /})).toHaveCount(0)
})

test('profile handles missing data and retries failed loads',async({page})=>{
 await setup(page)
 let attempts=0
 await page.route('**/rest/v1/pathfinders?**',route=>{
 expect(new URL(route.request().url()).searchParams.get('select')).not.toContain('honors')
 attempts++
 return attempts===1?route.fulfill({status:500,json:{message:'Profile unavailable'}}):route.fulfill({json:{...fixture,levels:[],years_active:[],staff_history:null,birth_date:null}})
 })
 await page.getByRole('button',{name:'Open profile for Justin Wu'}).click()
 await expect(page.getByRole('alert')).toContainText('Profile unavailable')
 await page.getByRole('button',{name:'Try again'}).click()
 await expect(page.getByText('No levels recorded',{exact:true})).toBeVisible()
 await expect(page.getByText('No staff years or titles recorded',{exact:true})).toBeVisible()
})

test('profile remains scrollable on mobile',async({page})=>{
 await page.setViewportSize({width:390,height:844})
 await setup(page)
 await page.getByRole('button',{name:'Open profile for Justin Wu'}).click()
 const dialog=page.getByRole('dialog',{name:'Member profile'})
 await expect(dialog.getByText('Friend (Basic)',{exact:false})).toBeVisible()
 const box=await dialog.boundingBox()
 expect(box!.width).toBeLessThanOrEqual(390)
 await page.screenshot({path:'test-results/profile-mobile.png'})
 await page.setViewportSize({width:1440,height:1000})
 await page.screenshot({path:'test-results/profile-desktop.png'})
})


test('group headings and outer areas replace Any without swallowing detail clicks',async({page})=>{
 await setup(page)
 const input=page.getByRole('combobox',{name:'Extracurricular',exact:true})
 await input.fill('Drums')
 await expect(page.getByRole('listbox',{name:'Extracurricular options'}).getByRole('option',{name:'Any',exact:true})).toHaveCount(0)
 await page.getByRole('option',{name:'Drums / Snare',exact:true}).click()
 await expect(page.getByRole('button',{name:'Remove Drums from Extracurricular',exact:true})).toHaveCount(0)
 await input.fill('Drums')
 await page.getByRole('option',{name:'Drums',exact:true}).click()
 await expect(page.getByRole('button',{name:'Remove Drums from Extracurricular',exact:true})).toBeVisible()
 const level=page.getByRole('combobox',{name:'Level Earned',exact:true})
 await level.fill('Friend'); await level.press('Enter')
 await expect(page.getByRole('button',{name:'Remove Friend from Level Earned',exact:true})).toBeVisible()
 const event=page.getByRole('combobox',{name:'Red Zone Events',exact:true})
 await event.fill('Archery')
 await page.getByRole('group',{name:'Archery',exact:true}).locator('..').click({position:{x:2,y:2}})
 await expect(page.getByRole('button',{name:'Remove Archery from Red Zone Events',exact:true})).toBeVisible()
})
