import { expect, test, type Page } from '@playwright/test'

const member = { id: 2, first_name: 'Justin', last_name: 'Wu', name: 'Justin Wu', status: 'staff', has_current_data: true, current_title: null, current_activities: ['Drill'],
 years_active: ['2023-24'], levels: [{name:'Friend',outcome:'basic',year:'2023-24'},{name:'Companion',outcome:'incomplete',year:null}], birth_date:'2000-01-02',notes:'Existing notes' }
const fixture = {...member,staff_history:{id:1,pathfinder_id:2,history:[{year:'2025-26',titles:['Friend Counselor','Drill Instructor']}]},
 drill:[{id:1,years:['2023-24'],team:'Precision'},{id:2,years:['2025-26'],team:'Adult'}],
 drum_corps:{history:[{year:'2023-24',drums:['Snare']}]},
 pbe:{history:[{year:'2021-22',books:['1 Kings','Ruth'],results:{Area:'1st Place',State:'Participation'}}]},
 tlt:{history:[{year:'2023-24',operations:['Teaching']}]},
 red_zone_drill_performance:[],red_zone_drum_performance:[],red_zone_honor_evaluations:[],red_zone_bible_events:[],red_zone_knots:[],red_zone_tents:[],red_zone_jump_rope:[],red_zone_archery:[],red_zone_lashing:[],
 red_zone_burning_twine:[{year:'2023-24',placement:'1st Place'}]}
async function setup(page:Page) {
 const user={id:'00000000-0000-0000-0000-000000000001',email:'staff@example.test',aud:'authenticated',role:'authenticated',app_metadata:{},user_metadata:{},created_at:'2026-01-01T00:00:00Z'}
 await page.route('http://127.0.0.1:54321/auth/v1/**',route=>route.fulfill({json:{access_token:'test-token',refresh_token:'test-refresh',token_type:'bearer',expires_in:3600,user}}))
 await page.route('http://127.0.0.1:54321/rest/v1/member_search?**',route=>route.fulfill({json:[member],headers:{'access-control-expose-headers':'content-range','content-range':'0-0/1'}}))
 await page.route('http://127.0.0.1:54321/rest/v1/pathfinders?**',route=>route.fulfill({json:route.request().method()==='PATCH'?{id:2}:fixture}))
 await page.route('**/rest/v1/honors_earned?**',route=>route.fulfill({json:[]}))
 await page.goto('/')
 await page.getByLabel('Email',{exact:true}).fill('staff@example.test')
 await page.getByLabel('Password',{exact:true}).fill('test-password')
 await page.getByRole('button',{name:'Sign in',exact:true}).click()
 await expect(page.getByRole('button',{name:'Open profile for Justin Wu'})).toBeVisible()
}

test('Add to Record preserves recipients across searches, confirms once and reports mixed outcomes',async({page})=>{
 await setup(page)
 await page.route('**/rest/v1/rpc/current_club_year',r=>r.fulfill({json:'2026-27'}))
 await page.route('**/rest/v1/staff_titles?**',r=>r.fulfill({json:[{title:'Club Director'}]}))
 await page.route('**/rest/v1/pbe_year_books?**',r=>r.fulfill({json:[]}))
 const second={...member,id:3,name:'Alex Example',first_name:'Alex',last_name:'Example',status:'parent'}
 const urls:string[]=[]
 await page.route('**/rest/v1/member_search?**',r=>{
  urls.push(r.request().url())
  const rows=r.request().url().includes('Alex')?[second]:[member]
  return r.fulfill({json:rows,headers:{'access-control-expose-headers':'content-range','content-range':'0-0/1'}})
 })
 let payload:Record<string,unknown>|undefined
 let release:(()=>void)|undefined
 await page.route('**/rest/v1/rpc/add_to_records',async r=>{payload=r.request().postDataJSON();await new Promise<void>(resolve=>{release=resolve});await r.fulfill({json:[{id:2,name:'Justin Wu',status:'added',year_added:true},{id:3,name:'Alex Example',status:'already',year_added:true}]})})
 await page.getByRole('button',{name:'Add',exact:true}).click()
 await page.getByRole('button',{name:'Add to Record',exact:true}).click()
 const dialog=page.getByRole('dialog',{name:'Add to Record',exact:true})
 await dialog.getByRole('combobox',{name:'Year to document',exact:true}).click()
 await expect(dialog.getByRole('option',{name:'2010-11',exact:true})).toHaveCount(1)
 await expect(dialog.getByRole('option',{name:'2009-10',exact:true})).toHaveCount(0)
 await dialog.getByRole('combobox',{name:'Year to document',exact:true}).fill('2025-26')
 await dialog.getByRole('combobox',{name:'Year to document',exact:true}).press('Enter')
 await dialog.getByLabel('Information category').selectOption('drums')
 await expect(dialog.getByLabel('Historical role')).toHaveCount(0)
 const beforeOptions=await dialog.getByRole('button',{name:'Select profiles'}).boundingBox()
 await dialog.getByRole('combobox',{name:'Instruments'}).click()
 expect((await dialog.getByRole('button',{name:'Select profiles'}).boundingBox())?.y).toBe(beforeOptions?.y)
 await dialog.getByRole('option',{name:'Snare',exact:true}).click()
 await dialog.getByRole('option',{name:'Bass',exact:true}).click()
 await page.keyboard.press('Escape')
 await dialog.getByRole('button',{name:'Select profiles'}).click()
 const dialogSize=await dialog.boundingBox()
 expect(dialogSize!.width).toBeGreaterThan(page.viewportSize()!.width * .9)
 await dialog.getByRole('checkbox',{name:'Select Justin Wu'}).check()
 await dialog.getByLabel('Name',{exact:true}).fill('Alex')
 await dialog.getByRole('button',{name:'Search records'}).click()
 await dialog.getByRole('checkbox',{name:'Select Alex Example'}).check()
 await expect(dialog).toContainText('Selected profiles (2)')
 expect(await dialog.getByRole('region',{name:'Selected profiles',exact:true}).evaluate(node => !!(node.compareDocumentPosition(document.querySelector('dialog table')!) & Node.DOCUMENT_POSITION_PRECEDING))).toBe(true)
 expect(urls.every(url=>new URL(url).searchParams.get('status')===null)).toBe(true)
 expect(new URL(urls[0]).searchParams.get('order')).toBe('sort_status.asc,sort_title.asc,sort_last_name.asc,sort_first_name.asc,id.asc')
 await page.screenshot({path:'test-results/recipient-search.png',fullPage:true})
 await dialog.getByRole('button',{name:'Finish / Done'}).click()
 const review=page.getByRole('dialog',{name:'Confirm Additions'})
 await expect(review).toContainText('Justin Wu'); await expect(review).toContainText('Alex Example')
 expect(payload).toBeUndefined()
 await expect(review.getByRole('button',{name:'Confirm',exact:true})).toBeVisible()
 await page.screenshot({path:'test-results/history-confirmation.png',fullPage:true})
 await review.getByRole('button',{name:'Confirm',exact:true}).click()
 const pending=page.getByRole('dialog',{name:'Adding to Records'})
 await expect(pending.getByRole('button',{name:'Close'})).toBeDisabled()
 await expect.poll(()=>!!release).toBe(true)
 release!()
 const result=page.getByRole('dialog',{name:'Records Updated'})
 await expect(result).toContainText('Added (1)'); await expect(result).toContainText('Already had this information (1)'); await expect(result).toContainText('Years Active updated')
 expect(payload).toEqual({p_ids:[2,3],p_year:'2025-26',p_entry:{kind:'drums',details:['Snare','Bass']}})
 await page.screenshot({path:'test-results/history-receipt.png',fullPage:true})
})

test('PBE includes every book for the year and only Staff titles restrict recipients',async({page})=>{
 await setup(page)
 await page.route('**/rest/v1/rpc/current_club_year',r=>r.fulfill({json:'2026-27'}))
 await page.route('**/rest/v1/staff_titles?**',r=>r.fulfill({json:[{title:'Club Director'}]}))
 await page.route('**/rest/v1/pbe_year_books?**',r=>r.fulfill({json:[{school_year:'2024-25',book_name:'Romans'},{school_year:'2024-25',book_name:'1 Corinthians'},{school_year:'2024-25',book_name:'2 Corinthians'},{school_year:'2026-27',book_name:'Mark'}]}))
 let payload:Record<string,unknown>|undefined
 await page.route('**/rest/v1/rpc/add_to_records',r=>{payload=r.request().postDataJSON();return r.fulfill({json:[{id:2,name:'Justin Wu',status:'added',year_added:true}]})})
 await page.getByRole('button',{name:'Add',exact:true}).click()
 await page.getByRole('button',{name:'Add to Record',exact:true}).click()
 const dialog=page.getByRole('dialog',{name:'Add to Record',exact:true})
 await dialog.getByLabel('Information category').selectOption('staff')
 await dialog.getByRole('combobox',{name:'Year to document',exact:true}).fill('2026-27')
 await dialog.getByRole('combobox',{name:'Year to document',exact:true}).press('Enter')
 await dialog.getByRole('combobox',{name:'Staff title',exact:true}).fill('Club Director')
 await dialog.getByRole('combobox',{name:'Staff title',exact:true}).press('Enter')
 const staffSearch=page.waitForRequest(r=>r.url().includes('/member_search?') && new URL(r.url()).searchParams.get('status')==='neq.pathfinder')
 await dialog.getByRole('button',{name:'Select profiles'}).click()
 await staffSearch
 await dialog.getByRole('checkbox',{name:'Select Justin Wu'}).check()
 await dialog.getByRole('button',{name:'Back to information'}).click()
 await dialog.getByLabel('Information category').selectOption('pbe')
 await dialog.getByRole('combobox',{name:'Year to document',exact:true}).fill('2024-25')
 await dialog.getByRole('combobox',{name:'Year to document',exact:true}).press('Enter')
 const books=dialog.getByRole('region',{name:'Bible books'})
 await expect(books).toContainText('Romans'); await expect(books).toContainText('1 Corinthians'); await expect(books).toContainText('2 Corinthians'); await expect(books).not.toContainText('Mark')
 await expect(books.getByRole('combobox')).toHaveCount(0)
 await expect(books.locator('ul')).toHaveCount(0)
 await expect(books).toContainText('Romans, 1 Corinthians, 2 Corinthians')
 await dialog.getByRole('combobox',{name:'PBE regions (optional)',exact:true}).click()
 await expect(dialog.getByRole('option',{name:'State / Participation',exact:true})).toBeDisabled()
 await expect(dialog.getByRole('option',{name:'Divisional / 1st Place',exact:true})).toBeDisabled()
 await dialog.getByRole('option',{name:'Area / 1st Place',exact:true}).click()
 await expect(dialog.getByRole('option',{name:'Area / 2nd Place',exact:true})).toBeDisabled()
 await dialog.getByRole('option',{name:'State / Participation',exact:true}).click()
 await dialog.getByRole('option',{name:'Union / 2nd Place',exact:true}).click()
 await expect(dialog.getByRole('option',{name:'Divisional / 1st Place',exact:true})).toBeEnabled()
 await page.keyboard.press('Escape')
 await dialog.getByRole('button',{name:'Remove State / Participation from PBE regions (optional)',exact:true}).click()
 await expect(dialog.getByRole('button',{name:'Remove Union / 2nd Place from PBE regions (optional)',exact:true})).toHaveCount(0)
 await dialog.getByRole('combobox',{name:'PBE regions (optional)',exact:true}).fill('State / Participation')
 await dialog.getByRole('combobox',{name:'PBE regions (optional)',exact:true}).press('Enter')
 await page.keyboard.press('Escape')
 await expect(dialog.getByRole('heading',{name:'Bible books',exact:true})).toHaveCount(0)
 await dialog.getByRole('button',{name:'Select profiles'}).click()
 await expect(dialog.getByRole('checkbox',{name:'Select Justin Wu'})).not.toBeChecked()
 await expect(dialog.getByRole('button',{name:'Finish / Done'})).toBeDisabled()
 await dialog.getByRole('checkbox',{name:'Select Justin Wu'}).check()
 await dialog.getByRole('button',{name:'Finish / Done'}).click()
 await page.getByRole('button',{name:'Confirm',exact:true}).click()
 await expect(page.getByRole('dialog',{name:'Records Updated'})).toBeVisible()
 await expect(page.getByRole('dialog',{name:'Records Updated'})).toContainText('Area: 1st Place; State: Participation')
 expect(payload).toEqual({p_ids:[2],p_year:'2024-25',p_entry:{kind:'pbe',details:['Romans','1 Corinthians','2 Corinthians'],results:{Area:'1st Place',State:'Participation'}}})
})

test('Honor lookup on mobile and batch errors retain the proposed addition',async({page})=>{
 await page.setViewportSize({width:390,height:844})
 await setup(page)
 await page.route('**/rest/v1/rpc/current_club_year',r=>r.fulfill({json:'2026-27'}))
 await page.route('**/rest/v1/staff_titles?**',r=>r.fulfill({json:[]}))
 await page.route('**/rest/v1/pbe_year_books?**',r=>r.fulfill({json:[]}))
 await page.route('**/rest/v1/honors?**',r=>r.fulfill({json:[{id:8,name:'Camping Skills I'}]}))
 let calls=0
 await page.route('**/rest/v1/rpc/add_to_records',r=>{calls++;return calls===1?r.fulfill({status:503,json:{message:'Connection unavailable'}}):r.fulfill({json:[{id:2,name:'Justin Wu',status:'error',reason:'Profile is no longer available.',year_added:false}]})})
 await page.getByRole('button',{name:'Add',exact:true}).click()
 await page.getByRole('button',{name:'Add to Record',exact:true}).click()
 const dialog=page.getByRole('dialog',{name:'Add to Record',exact:true})
 await expect(dialog.getByRole('button',{name:'Select profiles'})).toBeEnabled()
 await expect(dialog.getByRole('button',{name:'Remove 2026-27 from Year to document',exact:true})).toHaveCount(0)
 await expect(dialog.getByRole('button',{name:'Remove Basic from Outcome',exact:true})).toHaveCount(0)
 await dialog.getByRole('combobox',{name:'Year to document',exact:true}).fill('2026-27')
 await dialog.getByRole('combobox',{name:'Year to document',exact:true}).press('Enter')
 await dialog.getByLabel('Information category').selectOption('honor')
 await expect(dialog.getByLabel('Historical role')).toHaveCount(0)
 await dialog.getByLabel('Find an honor').fill('Camping')
 await dialog.getByRole('button',{name:'Camping Skills I',exact:true}).click()
 await page.screenshot({path:'test-results/history-mobile.png',fullPage:true})
 await dialog.getByRole('button',{name:'Select profiles'}).click()
 await dialog.getByRole('checkbox',{name:'Select Justin Wu'}).check()
 await dialog.getByRole('button',{name:'Finish / Done'}).click()
 await page.getByRole('button',{name:'Confirm',exact:true}).click()
 await expect(page.getByRole('alert')).toContainText('Connection unavailable')
 await page.getByRole('button',{name:'Back to confirmation'}).click()
 await expect(page.getByRole('dialog')).toContainText('Camping Skills I')
 await page.getByRole('button',{name:'Confirm',exact:true}).click()
 const result=page.getByRole('dialog',{name:'Completed with Errors'})
 await expect(result).toContainText('Not added (1)')
 await expect(result).toContainText('Profile is no longer available.')
 await result.getByRole('button',{name:'Review failed profiles'}).click()
 await expect(dialog.getByRole('button',{name:'Remove 2026-27 from Year to document',exact:true})).toBeVisible()
})

test('Add Record saves once, keeps failures editable, and refreshes Search',async({page})=>{
 await setup(page)
 await page.route('**/rest/v1/rpc/current_club_year',route=>route.fulfill({json:'2026-27'}))
 await page.route('**/rest/v1/staff_titles?**',route=>route.fulfill({json:['Club Director','Friend Counselor','Companion Counselor','Drill Instructor','Drum Corps Leader','Master Guide Leader'].map(title=>({title}))}))
 const requests: Record<string,unknown>[]=[]
 let release: (()=>void) | undefined
 await page.route('**/rest/v1/rpc/add_member_record',async route=>{
  requests.push(route.request().postDataJSON())
  if(requests.length===1) return route.fulfill({status:409,json:{code:'23505',message:'A profile with this first and last name already exists. Find the existing profile in Search.'}})
  await new Promise<void>(resolve=>{release=resolve})
  await route.fulfill({json:42})
 })
 await page.getByRole('button',{name:'Add',exact:true}).click()
 await page.getByRole('button',{name:'Add New Profile',exact:true}).click()
 const form=page.getByRole('dialog',{name:'Add New Profile',exact:true})
 await expect(form.getByLabel('Current Year')).toHaveValue('2026-2027')
 await form.getByLabel('First Name',{exact:true}).fill(' New ')
 await form.getByLabel('Last Name').fill('Member')
 await form.getByLabel('Birthday').fill('2001-02-03')
 await form.getByRole('combobox',{name:'Status',exact:true}).selectOption('Staff')
 await form.getByRole('combobox',{name:'Class/Title'}).click()
 await expect(form.locator('.level-name')).toHaveText(['Counselor','Instructor','Leader','Other'])
 await page.screenshot({path:'test-results/add-record-desktop.png',fullPage:true})
 await form.getByRole('option',{name:'Friend Counselor',exact:true}).click()
 await form.getByRole('option',{name:'Companion Counselor',exact:true}).click()
 await page.keyboard.press('Escape')
 await form.getByRole('button',{name:'Add',exact:true}).click()
 await form.getByRole('button',{name:/Confirm/}).click()
 const failure=page.getByRole('dialog',{name:'Unable to Add Record',exact:true})
 await expect(failure.getByRole('alert')).toContainText('A profile with this first and last name already exists.')
 await page.screenshot({path:'test-results/add-record-error.png',fullPage:true})
 await failure.getByRole('button',{name:'Back to form'}).click()
 await expect(form.getByLabel('First Name',{exact:true})).toHaveValue(' New ')
 await expect(page.getByRole('dialog',{name:'Record Added',exact:true})).toHaveCount(0)
 await form.getByRole('button',{name:'Add',exact:true}).click()
 await form.getByRole('button',{name:/Confirm/}).click()
 const pending=page.getByRole('dialog',{name:'Adding Record',exact:true})
 await expect(pending).toContainText('Saving the new profile')
 await page.screenshot({path:'test-results/add-record-loading.png',fullPage:true})
 await expect(pending.getByRole('button',{name:'Close',exact:true})).toBeDisabled()
 await page.keyboard.press('Escape')
 await expect(pending).toBeVisible()
 const refreshed=page.waitForRequest(r=>r.url().includes('/member_search?'))
 await expect.poll(()=>!!release).toBe(true)
 release!()
 const summary=page.getByRole('dialog',{name:'Record Added',exact:true})
 await expect(summary).toContainText('New Member')
 await expect(summary).toContainText('02/03/2001')
 await expect(summary).toContainText('Friend Counselor, Companion Counselor')
 await page.screenshot({path:'test-results/record-added.png',fullPage:true})
 await refreshed
 expect(requests).toHaveLength(2)
 expect(requests[0]).toEqual(requests[1])
 expect(requests[1]).toMatchObject({p_first_name:'New',p_last_name:'Member',p_birth_date:'2001-02-03',p_status:'staff',p_current_title:['Friend Counselor','Companion Counselor'],p_school_year:'2026-27'})
 await summary.getByRole('button',{name:'Close',exact:true}).click()
 await expect(page.getByRole('button',{name:'Add New Profile',exact:true})).toBeFocused()
})

test('Add confirmation expires and status changes clear incompatible titles',async({page})=>{
 await page.setViewportSize({width:390,height:844})
 await setup(page)
 await page.route('**/rest/v1/rpc/current_club_year',route=>route.fulfill({json:'2026-27'}))
 await page.route('**/rest/v1/staff_titles?**',route=>route.fulfill({json:[]}))
 let writes=0
 await page.route('**/rest/v1/rpc/add_member_record',route=>{writes++;return route.fulfill({json:43})})
 await page.getByRole('button',{name:'Add',exact:true}).click()
 await page.getByRole('button',{name:'Add New Profile',exact:true}).click()
 const form=page.getByRole('dialog',{name:'Add New Profile',exact:true})
 await form.getByLabel('First Name',{exact:true}).fill('Example')
 await form.getByRole('combobox',{name:'Status',exact:true}).selectOption('Pathfinder')
 const classSelect=form.getByRole('combobox',{name:'Class/Title'})
 await classSelect.selectOption('Friend')
 await classSelect.selectOption('Companion')
 await expect(classSelect).toHaveValue('Companion')
 await expect(classSelect.locator('option:checked')).toHaveCount(1)
 await form.getByRole('button',{name:'Add',exact:true}).click()
 await expect(form.getByRole('button',{name:/Confirm/})).toBeVisible()
 await form.getByRole('combobox',{name:'Status',exact:true}).selectOption('Parent')
 await expect(form.getByRole('button',{name:'Add',exact:true})).toBeVisible()
 await expect(form.getByLabel('Class/Title')).toBeDisabled()
 await page.screenshot({path:'test-results/add-record-mobile.png',fullPage:true})
 await form.getByRole('button',{name:'Add',exact:true}).click()
 await expect(form.getByRole('button',{name:'Add',exact:true})).toBeVisible({timeout:7000})
 expect(writes).toBe(0)
 await form.getByRole('button',{name:'Add',exact:true}).click()
 const request=page.waitForRequest('**/rest/v1/rpc/add_member_record')
 await form.getByRole('button',{name:/Confirm/}).click()
 expect((await request).postDataJSON()).toMatchObject({p_current_title:null,p_birth_date:null,p_status:'parent'})
 await expect(page.getByRole('dialog',{name:'Record Added',exact:true})).toContainText('N/A')
})

test('current results expose First Last Status Title and activities only',async({page})=>{
 await setup(page)
 await expect(page.getByRole('columnheader')).toHaveText(['First Name','Last Name','Status','Class/Titles','Current activities'])
 await expect(page.getByRole('row').last()).toContainText('Staff')
 await expect(page.getByRole('row').last()).toContainText('Not recorded')
 await expect(page.getByRole('row').last().getByRole('cell').last()).toHaveText('N/A')
 const status=page.getByRole('combobox',{name:'Status',exact:true})
 await expect(status.locator('option')).toHaveText(['Any','Pathfinder','Staff','Parent','Not Active'])
 const request=page.waitForRequest(r=>r.url().includes('status=eq.not_active'))
 await status.selectOption('Not Active')
 await page.getByRole('button',{name:'Search records'}).click()
 await request
})

test('role histories retain year detail links and nested honors focus',async({page})=>{
 await setup(page)
 await page.getByRole('button',{name:'Open profile for Justin Wu'}).click()
 const profile=page.getByRole('dialog',{name:'Member profile'})
 await expect(profile).toContainText('01/02/2000')
 const pf=profile.getByRole('region',{name:'Pathfinder history'})
 const staff=profile.getByRole('region',{name:'Staff history'})
 await expect(pf).toContainText('Friend (Basic)')
 await expect(pf).toContainText('Companion (Incomplete)')
 await expect(pf).toContainText('Year unknown')
 await expect(pf).toContainText('Precision')
 await expect(pf).toContainText('Snare')
 await expect(pf).not.toContainText('1 Kings, Ruth')
 await expect(pf).toContainText('Area (1st), State (P)')
 await expect(pf).toContainText('Teaching')
 await expect(pf).toContainText('Adult')
 await expect(staff).not.toContainText('Adult')
 await expect(staff).toContainText('Friend Counselor, Drill Instructor')
 await page.route('**/rest/v1/honors_earned?**',route=>route.fulfill({json:[{id:1,year_earned:'2023-24',honors:{name:'Camping Skills I'}}]}))
 await profile.getByRole('button',{name:'View Honors'}).click()
 const honors=page.getByRole('dialog',{name:'Honors',exact:true})
 await expect(honors).toContainText('Camping Skills I')
 await expect(honors).toContainText('2023-24')
 await expect(honors).not.toContainText('Staff')
 await expect(honors).not.toContainText('Pathfinder')
 await page.keyboard.press('Escape')
 await expect(profile.getByRole('button',{name:'View Honors'})).toBeFocused()
 await page.keyboard.press('Escape')
 await expect(page.getByRole('button',{name:'Open profile for Justin Wu'})).toBeFocused()
})

test('Notes preserve paragraphs and report saves and failures',async({page})=>{
 await setup(page)
 await page.getByRole('button',{name:'Open profile for Justin Wu'}).click()
 const notes=page.getByLabel('Notes',{exact:true})
 await expect(notes).toHaveValue('Existing notes')
 await notes.fill('First sentence.\n\nSecond paragraph.')
 const request=page.waitForRequest(r=>r.method()==='PATCH')
 await page.getByRole('button',{name:'Save Notes'}).click()
 expect((await request).postDataJSON()).toEqual({notes:'First sentence.\n\nSecond paragraph.'})
 await expect(page.getByText('Notes saved',{exact:true})).toBeVisible()
 await page.route('**/rest/v1/pathfinders?**',route=>route.fulfill({status:500,json:{message:'Save unavailable'}}))
 await notes.fill('Keep this unsaved text')
 await page.getByRole('button',{name:'Save Notes'}).click()
 await expect(page.getByRole('alert')).toContainText('Save unavailable')
 await expect(notes).toHaveValue('Keep this unsaved text')
})

test('shared years constrain every category with OR bubbles and AND categories',async({page})=>{
 await setup(page)
 const years=page.getByRole('combobox',{name:'Years',exact:true})
 await years.fill('2023-24'); await years.press('Enter')
 const level=page.getByRole('combobox',{name:'Level Earned',exact:true})
 await level.fill('Friend')
 await expect(page.getByRole('option',{name:'Friend (2023-24)',exact:true})).toHaveCount(0)
 await page.getByRole('option',{name:'Friend / Basic',exact:true}).click()
 await level.fill('Friend / Advanced');await level.press('Enter')
 const activity=page.getByRole('combobox',{name:'Extracurricular',exact:true})
 await activity.fill('Drums / Snare');await activity.press('Enter')
 await activity.fill('TLT / Teaching');await activity.press('Enter')
 const event=page.getByRole('combobox',{name:'Red Zone Events',exact:true})
 await event.fill('Burning Twine / 1st Place');await event.press('Enter');await event.press('Escape')
 const request=page.waitForRequest(r=>r.url().includes('or='))
 await page.getByRole('button',{name:'Search records'}).click()
 const expression=new URL((await request).url()).searchParams.get('or')!
 expect(expression).toContain('(and(or(levels.cs.')
 expect(expression).toContain('),or(search_activity_details.cs.')
 expect(expression).toContain('),or(search_event_details.cs.')
 const decoded=expression.replaceAll('\\"','"')
 expect(decoded).toContain('"outcome":"basic","year":"2023-24"')
 expect(decoded).toContain('"outcome":"advanced","year":"2023-24"')
 expect(decoded).toContain('"name":"Drums","detail":"Snare","year":"2023-24"')
 expect(decoded).toContain('"name":"TLT","detail":"Teaching","year":"2023-24"')
 expect(decoded).toContain('"name":"Burning Twine","detail":"1st Place","year":"2023-24"')
 expect(expression).not.toContain('search_years')
 await page.getByRole('button',{name:'Clear filters'}).click()
 await expect(page.getByRole('button',{name:/^Remove /})).toHaveCount(0)
})

test('profile handles missing data and retries failed loads',async({page})=>{
 await setup(page)
 let attempts=0
 await page.route('**/rest/v1/pathfinders?**',route=>{
 expect(new URL(route.request().url()).searchParams.get('select')).not.toContain('honors')
 attempts++
 return attempts===1?route.fulfill({status:500,json:{message:'Profile unavailable'}}):route.fulfill({json:{...fixture,levels:[],years_active:[],staff_history:null,birth_date:null}})
 })
 await page.getByRole('button',{name:'Open profile for Justin Wu'}).click()
 await expect(page.getByRole('alert')).toContainText('Profile unavailable')
 await page.getByRole('button',{name:'Try again'}).click()
 await expect(page.getByText('No levels recorded',{exact:true})).toBeVisible()
 await expect(page.getByText('No staff years or titles recorded',{exact:true})).toBeVisible()
})

test('profile remains scrollable on mobile',async({page})=>{
 await page.setViewportSize({width:390,height:844})
 await setup(page)
 await page.getByRole('button',{name:'Open profile for Justin Wu'}).click()
 const dialog=page.getByRole('dialog',{name:'Member profile'})
 await expect(dialog.getByText('Friend (Basic)',{exact:false})).toBeVisible()
 const box=await dialog.boundingBox()
 expect(box!.width).toBeLessThanOrEqual(390)
 await page.screenshot({path:'test-results/profile-mobile.png'})
 await page.setViewportSize({width:1440,height:1000})
 await page.screenshot({path:'test-results/profile-desktop.png'})
})


test('group headings and outer areas replace Any without swallowing detail clicks',async({page})=>{
 await setup(page)
 const input=page.getByRole('combobox',{name:'Extracurricular',exact:true})
 await input.fill('Drums')
 await expect(page.getByRole('listbox',{name:'Extracurricular options'}).getByRole('option',{name:'Any',exact:true})).toHaveCount(0)
 await page.getByRole('option',{name:'Drums / Snare',exact:true}).click()
 await expect(page.getByRole('button',{name:'Remove Drums from Extracurricular',exact:true})).toHaveCount(0)
 await input.fill('Drums')
 await page.getByRole('option',{name:'Drums',exact:true}).click()
 await expect(page.getByRole('button',{name:'Remove Drums from Extracurricular',exact:true})).toBeVisible()
 const level=page.getByRole('combobox',{name:'Level Earned',exact:true})
 await level.fill('Friend'); await level.press('Enter')
 await expect(page.getByRole('button',{name:'Remove Friend from Level Earned',exact:true})).toBeVisible()
 const event=page.getByRole('combobox',{name:'Red Zone Events',exact:true})
 await event.fill('Archery')
 await page.getByRole('group',{name:'Archery',exact:true}).locator('..').click({position:{x:2,y:2}})
 await expect(page.getByRole('button',{name:'Remove Archery from Red Zone Events',exact:true})).toBeVisible()
})


test('PBE search links region and placement bubbles to the selected year',async({page})=>{
 await setup(page)
 await page.getByRole('combobox',{name:'Years',exact:true}).fill('2024-25')
 await page.getByRole('combobox',{name:'Years',exact:true}).press('Enter')
 await page.keyboard.press('Escape')
 await page.getByRole('combobox',{name:'Extracurricular',exact:true}).click()
 await page.getByRole('combobox',{name:'PBE region',exact:true}).selectOption('State')
 await page.getByRole('option',{name:'PBE / State / 1st Place',exact:true}).click()
 await page.getByRole('option',{name:'PBE / State / Participation',exact:true}).click()
 await expect(page.getByRole('button',{name:'Remove PBE / State / 1st Place from Extracurricular',exact:true})).toBeVisible()
 await page.getByRole('combobox',{name:'PBE region',exact:true}).selectOption('Union')
 await expect(page.getByRole('option',{name:'PBE / Union / 2nd Place',exact:true})).toBeVisible()
 await page.keyboard.press('Escape')
 const request=page.waitForRequest(r=>r.url().includes('/member_search?') && r.url().includes('search_activity_details'))
 await page.getByRole('button',{name:'Search records'}).click()
 const expression=new URL((await request).url()).searchParams.get('or')!.replaceAll('\\"','"')
 expect(expression).toContain('"name":"PBE","detail":"State / 1st Place","year":"2024-25"')
 expect(expression).toContain('"name":"PBE","detail":"State / Participation","year":"2024-25"')
 await page.getByRole('button',{name:'Clear filters'}).click()
 await page.getByRole('combobox',{name:'Extracurricular',exact:true}).click()
 await expect(page.getByRole('combobox',{name:'PBE region',exact:true})).toHaveValue('')
})
